# Generated by Django 4.2.30 on 2026-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='email_peminjam',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
