# Generated by Django 4.2.30 on 2026-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reservasi_email_peminjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='buku/'),
        ),
    ]
